# Churn em Marketing

O **churn** refere-se à taxa de perda de clientes que deixam de fazer negócios com uma empresa. É um indicador importante, pois:

- **Impacto na Receita**: Quanto mais clientes cancelam seus serviços, maior a perda de receita.
- **Indicador de Satisfação**: Pode sinalizar insatisfação dos clientes em relação aos produtos ou serviços oferecidos.

## Estratégias para Reduzir o Churn

As empresas buscam diversas estratégias para reduzir o churn, incluindo:

- **Melhoria da Qualidade**: Aumentar a qualidade dos produtos e serviços oferecidos.
- **Suporte ao Cliente**: Oferecer suporte de qualidade e mais rápido.
- **Programas de Fidelidade**: Criar programas que incentivem a lealdade dos clientes.

Manter os clientes satisfeitos é fundamental para aumentar a retenção e a receita da empresa.

In [55]:
import pandas as pd
import requests

In [56]:


url = 'https://cdn3.gnarususercontent.com.br/2929-pandas/dataset-telecon.json'

try:
    response = requests.get(url)
    response.raise_for_status()  # Garante que a requisição foi bem-sucedida
    data = response.json()  # Converte a resposta JSON para um dicionário/lista
    df_churn = pd.DataFrame(data)  # Converte para DataFrame
    print(df_churn.head())
except Exception as e:
    print(f"Ocorreu um erro: {e}")

   id_cliente Churn                                            cliente  \
0  0002-ORFBO   nao  {'genero': 'feminino', 'idoso': 0, 'parceiro':...
1  0003-MKNFE   nao  {'genero': 'masculino', 'idoso': 0, 'parceiro'...
2  0004-TLHLJ   sim  {'genero': 'masculino', 'idoso': 0, 'parceiro'...
3  0011-IGKFF   sim  {'genero': 'masculino', 'idoso': 1, 'parceiro'...
4  0013-EXCHZ   sim  {'genero': 'feminino', 'idoso': 1, 'parceiro':...

                                            telefone  \
0  {'servico_telefone': 'sim', 'varias_linhas': '...
1  {'servico_telefone': 'sim', 'varias_linhas': '...
2  {'servico_telefone': 'sim', 'varias_linhas': '...
3  {'servico_telefone': 'sim', 'varias_linhas': '...
4  {'servico_telefone': 'sim', 'varias_linhas': '...

                                            internet  \
0  {'servico_internet': 'DSL', 'seguranca_online'...
1  {'servico_internet': 'DSL', 'seguranca_online'...
2  {'servico_internet': 'fibra otica', 'seguranca...
3  {'servico_internet': 'fibra otica', 'seguranca...
4  {'servico_internet': 'fibra otica', 'seguranca...

                                               conta
0  {'contrato': None, 'faturamente_eletronico': N...
1  {'contrato': 'mes a mes', 'faturamente_eletron...
2  {'contrato': 'mes a mes', 'faturamente_eletron...
3  {'contrato': 'mes a mes', 'faturamente_eletron...
4  {'contrato': 'mes a mes', 'faturamente_eletron...

In [57]:
df_churn

,id_cliente,Churn,cliente,telefone,internet,conta
0,0002-ORFBO,nao,"{'genero': 'feminino', 'idoso': 0, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': None, 'faturamente_eletronico': N..."
1,0003-MKNFE,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': 'mes a mes', 'faturamente_eletron..."
2,0004-TLHLJ,sim,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
3,0011-IGKFF,sim,"{'genero': 'masculino', 'idoso': 1, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
4,0013-EXCHZ,sim,"{'genero': 'feminino', 'idoso': 1, 'parceiro':...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
...,...,...,...,...,...,...
7339,5172-RKOCB,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'dois anos', 'faturamente_eletron..."
7340,1934-MKPXS,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'nao', 'seguranca_online'...","{'contrato': 'um ano', 'faturamente_eletronico..."
7341,5959-BELXA,sim,"{'genero': 'masculino', 'idoso': 1, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'fibra otica', 'seguranca...","{'contrato': 'mes a mes', 'faturamente_eletron..."
7342,3601-UTZXO,,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'nao', 'seguranca_online'...","{'contrato': 'um ano', 'faturamente_eletronico..."
7343,4452-QIIEB,nao,"{'genero': 'masculino', 'idoso': 0, 'parceiro'...","{'servico_telefone': 'sim', 'varias_linhas': '...","{'servico_internet': 'DSL', 'seguranca_online'...","{'contrato': 'mes a mes', 'faturamente_eletron..."

In [58]:
df_churn['conta'][0]

{'contrato': None,
 'faturamente_eletronico': None,
 'metodo_pagamento': None,
 'cobranca': {'mensal': None, 'Total': None}}

In [59]:
pd.json_normalize(df_churn['conta'][0])

,contrato,faturamente_eletronico,metodo_pagamento,cobranca.mensal,cobranca.Total
0,None,None,None,None,None

In [60]:
pd.json_normalize(df_churn['telefone'][0])

  servico_telefone varias_linhas
0              sim           nao

Transformando dados em Tabela

In [61]:
import requests
import json

url = "https://cdn3.gnarususercontent.com.br/2929-pandas/dataset-telecon.json"

try:
    # Faz o request para obter o JSON
    response = requests.get(url)
    response.raise_for_status()  # Verifica se houve erro na requisição
    
    # Converte a resposta para um objeto JSON (dicionário ou lista)
    json_bruto = response.json()
    
    # Se precisar visualizar a estrutura do JSON antes de normalizar:
    print(json.dumps(json_bruto, indent=2))  
    
    # Normaliza se for necessário
    df_churn = pd.json_normalize(json_bruto)

    print(df_churn.head())
    
except Exception as e:
    print(f"Ocorreu um erro: {e}")

[
  {
    "id_cliente": "0002-ORFBO",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": 9
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "nao",
      "backup_online": "sim",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": null,
      "faturamente_eletronico": null,
      "metodo_pagamento": null,
      "cobranca": {
        "mensal": null,
        "Total": null
      }
    }
  },
  {
    "id_cliente": "0003-MKNFE",
    "Churn": "nao",
    "cliente": {
      "genero": "masculino",
      "idoso": 0,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 9
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cheque pelo correio",
      "cobranca": {
        "mensal": 59.9,
        "Total": "542.4"
      }
    }
  },
  {
    "id_cliente": "0004-TLHLJ",
    "Churn": "sim",
    "cliente": {
      "genero": "masculino",
      "idoso": 0,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 4
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 73.9,
        "Total": "280.85"
      }
    }
  },
  {
    "id_cliente": "0011-IGKFF",
    "Churn": "sim",
    "cliente": {
      "genero": "masculino",
      "idoso": 1,
      "parceiro": "sim",
      "dependentes": "nao",
      "tempo_servico": 13
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "nao",
      "tv_streaming": "sim",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 98.0,
        "Total": "1237.85"
      }
    }
  },
  {
    "id_cliente": "0013-EXCHZ",
    "Churn": "sim",
    "cliente": {
      "genero": "feminino",
      "idoso": 1,
      "parceiro": "sim",
      "dependentes": "nao",
      "tempo_servico": 3
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque pelo correio",
      "cobranca": {
        "mensal": 83.9,
        "Total": "267.4"
      }
    }
  },
  {
    "id_cliente": "0013-MHZWF",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "nao",
      "dependentes": "sim",
      "tempo_servico": 9
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cartao de credito (automatico)",
      "cobranca": {
        "mensal": 69.4,
        "Total": "571.45"
      }
    }
  },
  {
    "id_cliente": "0013-SMEOE",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 1,
      "parceiro": "sim",
      "dependentes": "nao",
      "tempo_servico": 71
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "sim",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "transferencia bancaria (automatica)",
      "cobranca": {
        "mensal": 109.7,
        "Total": "7904.25"
      }
    }
  },
  {
    "id_cliente": "0014-BMAQU",
    "Churn": "nao",
    "cliente": {
      "genero": "masculino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "nao",
      "tempo_servico": 63
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "sim",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "sim",
      "tv_streaming": "nao",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cartao de credito (automatico)",
      "cobranca": {
        "mensal": 84.65,
        "Total": "5377.8"
      }
    }
  },
  {
    "id_cliente": "0015-UOCOJ",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 1,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 7
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "sim",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 48.2,
        "Total": "340.35"
      }
    }
  },
  {
    "id_cliente": "0016-QLJIS",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": null
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "sim",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque pelo correio",
      "cobranca": {
        "mensal": 90.45,
        "Total": "5957.9"
      }
    }
  },
  {
    "id_cliente": "0017-DInaoC",
    "Churn": "nao",
    "cliente": {
      "genero": "masculino",
      "idoso": 0,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 54
    },
    "telefone": {
      "servico_telefone": "nao",
      "varias_linhas": "sem servico de telefone"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "sim",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cartao de credito (automatico)",
      "cobranca": {
        "mensal": 45.2,
        "Total": "2460.55"
      }
    }
  },
  {
    "id_cliente": "0017-IUDMW",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": 72
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "sim",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cartao de credito (automatico)",
      "cobranca": {
        "mensal": 116.8,
        "Total": "8456.75"
      }
    }
  },
  {
    "id_cliente": "0018-NYROU",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "nao",
      "tempo_servico": 5
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 68.95,
        "Total": "351.5"
      }
    }
  },
  {
    "id_cliente": "0019-EFAEP",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 72
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "sim",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "nao",
      "tv_streaming": "sim",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "transferencia bancaria (automatica)",
      "cobranca": {
        "mensal": 101.3,
        "Total": "7261.25"
      }
    }
  },
  {
    "id_cliente": "0019-GFNTW",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 56
    },
    "telefone": {
      "servico_telefone": "nao",
      "varias_linhas": "sem servico de telefone"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "sim",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "sim",
      "tv_streaming": "nao",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "transferencia bancaria (automatica)",
      "cobranca": {
        "mensal": 45.05,
        "Total": "2560.1"
      }
    }
  },
  {
    "id_cliente": "0020-INWCK",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": 71
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "dois anos",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cartao de credito (automatico)",
      "cobranca": {
        "mensal": 95.75,
        "Total": "6849.4"
      }
    }
  },
  {
    "id_cliente": "0020-JDNXP",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": 34
    },
    "telefone": {
      "servico_telefone": "nao",
      "varias_linhas": "sem servico de telefone"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "sim",
      "backup_online": "nao",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "sim",
      "tv_streaming": "sim",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "um ano",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cheque pelo correio",
      "cobranca": {
        "mensal": 61.25,
        "Total": "1993.2"
      }
    }
  },
  {
    "id_cliente": "0021-IKXGC",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 1,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 1
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 72.1,
        "Total": "72.1"
      }
    }
  },
  {
    "id_cliente": "0022-TCJCI",
    "Churn": "sim",
    "cliente": {
      "genero": "masculino",
      "idoso": 1,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 45
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "sim",
      "backup_online": "nao",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "sim"
    },
    "conta": {
      "contrato": "um ano",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cartao de credito (automatico)",
      "cobranca": {
        "mensal": 62.7,
        "Total": "2791.5"
      }
    }
  },
  {
    "id_cliente": "0023-HGHWL",
    "Churn": "sim",
    "cliente": {
      "genero": "masculino",
      "idoso": 1,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 1
    },
    "telefone": {
      "servico_telefone": "nao",
      "varias_linhas": "sem servico de telefone"
    },
    "internet": {
      "servico_internet": "DSL",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "nao",
      "tv_streaming": "nao",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 25.1,
        "Total": "25.1"
      }
    }
  },
  {
    "id_cliente": "0023-UYUPN",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 1,
      "parceiro": "sim",
      "dependentes": "nao",
      "tempo_servico": 50
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "nao",
      "seguranca_online": "sem servico de internet",
      "backup_online": "sem servico de internet",
      "protecao_dispositivo": "sem servico de internet",
      "suporte_tecnico": "sem servico de internet",
      "tv_streaming": "sem servico de internet",
      "filmes_streaming": "sem servico de internet"
    },
    "conta": {
      "contrato": "um ano",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 25.2,
        "Total": "1306.3"
      }
    }
  },
  {
    "id_cliente": "0023-XUOPT",
    "Churn": "sim",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "nao",
      "tempo_servico": 13
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "sim",
      "protecao_dispositivo": "sim",
      "suporte_tecnico": "nao",
      "tv_streaming": "sim",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 94.1,
        "Total": "1215.6"
      }
    }
  },
  {
    "id_cliente": "0027-KWYKW",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": 23
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "sim"
    },
    "internet": {
      "servico_internet": "fibra otica",
      "seguranca_online": "nao",
      "backup_online": "nao",
      "protecao_dispositivo": "nao",
      "suporte_tecnico": "nao",
      "tv_streaming": "sim",
      "filmes_streaming": "nao"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "sim",
      "metodo_pagamento": "cheque eletronico",
      "cobranca": {
        "mensal": 83.75,
        "Total": "1849.95"
      }
    }
  },
  {
    "id_cliente": "0030-FNXPP",
    "Churn": "nao",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "nao",
      "dependentes": "nao",
      "tempo_servico": 3
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "nao",
      "seguranca_online": "sem servico de internet",
      "backup_online": "sem servico de internet",
      "protecao_dispositivo": "sem servico de internet",
      "suporte_tecnico": "sem servico de internet",
      "tv_streaming": "sem servico de internet",
      "filmes_streaming": "sem servico de internet"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cheque pelo correio",
      "cobranca": {
        "mensal": 19.85,
        "Total": "57.2"
      }
    }
  },
  {
    "id_cliente": "0031-PVLZI",
    "Churn": "sim",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": 4
    },
    "telefone": {
      "servico_telefone": "sim",
      "varias_linhas": "nao"
    },
    "internet": {
      "servico_internet": "nao",
      "seguranca_online": "sem servico de internet",
      "backup_online": "sem servico de internet",
      "protecao_dispositivo": "sem servico de internet",
      "suporte_tecnico": "sem servico de internet",
      "tv_streaming": "sem servico de internet",
      "filmes_streaming": "sem servico de internet"
    },
    "conta": {
      "contrato": "mes a mes",
      "faturamente_eletronico": "nao",
      "metodo_pagamento": "cheque pelo correio",
      "cobranca": {
        "mensal": 20.35,
        "Total": "76.35"
      }
    }
  },
  {
    "id_cliente": "0032-PGELS",
    "Churn": "sim",
    "cliente": {
      "genero": "feminino",
      "idoso": 0,
      "parceiro": "sim",
      "dependentes": "sim",
      "tempo_servico": 1
    },
    "telefone": {

In [62]:
df_churn.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,None
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.4
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.4

# Dicionário de Dados

| Coluna                           | Descrição                                           |
|----------------------------------|-----------------------------------------------------|
| id_cliente                       | Identificador único do cliente                       |
| Churn                            | Indica se o cliente cancelou o serviço (sim/não)   |
| cliente.genero                   | Gênero do cliente (masculino/feminino)             |
| cliente.idoso                    | Indica se o cliente é idoso (0 = não, 1 = sim)     |
| cliente.parceiro                 | Indica se o cliente tem parceiro (sim/não)          |
| cliente.dependentes              | Indica se o cliente tem dependentes (sim/não)      |
| cliente.tempo_servico            | Tempo de serviço em meses                           |
| telefone.servico_telefone        | Indica se o cliente possui serviço de telefone (sim/não) |
| telefone.varias_linhas           | Indica se o cliente possui várias linhas telefônicas (sim/não) |
| internet.servico_internet        | Tipo de serviço de internet (DSL, fibra ótica, etc.) |
| internet.backup_online           | Indica se o cliente possui backup online (sim/não)  |
| internet.protecao_dispositivo    | Indica se o cliente possui proteção de dispositivo (sim/não) |
| internet.suporte_tecnico         | Indica se o cliente possui suporte técnico (sim/não) |
| internet.tv_streaming            | Indica se o cliente possui serviço de TV streaming (sim/não) |
| internet.filmes_streaming        | Indica se o cliente possui serviço de filmes streaming (sim/não) |
| conta.contrato                   | Tipo de contrato (mensal, anual, etc.)              |
| conta.faturamente_eletronico     | Indica se o cliente utiliza faturamento eletrônico (sim/não) |
| conta.metodo_pagamento           | Método de pagamento utilizado (cheque, cartão, etc.) |
| conta.cobranca.mensal            | Valor da cobrança mensal em reais                   |
| conta.cobranca.Total             | Valor total gasto pelo cliente em reais             |

In [63]:
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7344 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7344 non-null   object
 1   Churn                          7344 non-null   object
 2   cliente.genero                 7344 non-null   object
 3   cliente.idoso                  7344 non-null   int64
 4   cliente.parceiro               7344 non-null   object
 5   cliente.dependentes            7344 non-null   object
 6   cliente.tempo_servico          7336 non-null   float64
 7   telefone.servico_telefone      7344 non-null   object
 8   telefone.varias_linhas         7344 non-null   object
 9   internet.servico_internet      7344 non-null   object
 10  internet.seguranca_online      7344 non-null   object
 11  internet.backup_online         7344 non-null   object
 12  internet.protecao_dispositivo  7344 non-null   object
 13  internet.suporte_tecnico       7344 non-null   object
 14  internet.tv_streaming          7344 non-null   object
 15  internet.filmes_streaming      7344 non-null   object
 16  conta.contrato                 7312 non-null   object
 17  conta.faturamente_eletronico   7326 non-null   object
 18  conta.metodo_pagamento         7317 non-null   object
 19  conta.cobranca.mensal          7326 non-null   float64
 20  conta.cobranca.Total           7328 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.2+ MB

In [64]:
df_churn[df_churn['conta.cobranca.Total'] == ' '].head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
975,1371-DWPAZ,nao,feminino,0,sim,sim,0.0,nao,sem servico de telefone,DSL,...,sim,sim,sim,sim,nao,dois anos,nao,cartao de credito (automatico),56.05,
1775,2520-SGTTA,nao,feminino,0,sim,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,nao,cheque pelo correio,20.00,
1955,2775-SEFEE,nao,masculino,0,nao,sim,0.0,sim,sim,DSL,...,sim,nao,sim,nao,nao,dois anos,sim,transferencia bancaria (automatica),61.90,
2075,2923-ARZLG,nao,masculino,0,sim,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,cheque pelo correio,19.70,
2232,3115-CZMZD,nao,masculino,0,nao,sim,0.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,nao,cheque pelo correio,20.25,

In [65]:
df_churn[df_churn['conta.cobranca.Total'] == ' '][
    ['cliente.tempo_servico','conta.contrato','conta.cobranca.mensal','conta.cobranca.Total']
]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,0.0,dois anos,56.05,
1775,0.0,dois anos,20.00,
1955,0.0,dois anos,61.90,
2075,0.0,dois anos,19.70,
2232,0.0,dois anos,20.25,
2308,0.0,dois anos,25.35,
2930,0.0,dois anos,73.35,
3134,0.0,dois anos,25.75,
3203,0.0,dois anos,52.55,
4169,0.0,dois anos,80.85,
5599,0.0,dois anos,19.85,

In [66]:
idx = df_churn[df_churn['conta.cobranca.Total'] == ' '].index

In [67]:
df_churn.loc[idx,'conta.cobranca.Total'] =  df_churn.loc[idx,'conta.cobranca.mensal'] * 24

In [68]:
df_churn.loc[idx,'cliente.tempo_servico'] =24

In [69]:
df_churn.loc[idx][
    ['cliente.tempo_servico','conta.contrato','conta.cobranca.mensal','conta.cobranca.Total']
]

,cliente.tempo_servico,conta.contrato,conta.cobranca.mensal,conta.cobranca.Total
975,24.0,dois anos,56.05,1345.2
1775,24.0,dois anos,20.00,480.0
1955,24.0,dois anos,61.90,1485.6
2075,24.0,dois anos,19.70,472.8
2232,24.0,dois anos,20.25,486.0
2308,24.0,dois anos,25.35,608.4
2930,24.0,dois anos,73.35,1760.4
3134,24.0,dois anos,25.75,618.0
3203,24.0,dois anos,52.55,1261.2
4169,24.0,dois anos,80.85,1940.4
5599,24.0,dois anos,19.85,476.4

In [70]:
df_churn['conta.cobranca.Total'] = df_churn['conta.cobranca.Total'].astype('float')

In [71]:
df_churn.head()

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
0,0002-ORFBO,nao,feminino,0,sim,sim,9.0,sim,nao,DSL,...,sim,nao,sim,sim,nao,None,None,None,NaN,NaN
1,0003-MKNFE,nao,masculino,0,nao,nao,9.0,sim,sim,DSL,...,nao,nao,nao,nao,sim,mes a mes,nao,cheque pelo correio,59.9,542.40
2,0004-TLHLJ,sim,masculino,0,nao,nao,4.0,sim,nao,fibra otica,...,nao,sim,nao,nao,nao,mes a mes,sim,cheque eletronico,73.9,280.85
3,0011-IGKFF,sim,masculino,1,sim,nao,13.0,sim,nao,fibra otica,...,sim,sim,nao,sim,sim,mes a mes,sim,cheque eletronico,98.0,1237.85
4,0013-EXCHZ,sim,feminino,1,sim,nao,3.0,sim,nao,fibra otica,...,nao,nao,sim,sim,nao,mes a mes,sim,cheque pelo correio,83.9,267.40

Tratando dados vazios

In [72]:
for col in df_churn.columns:
    print(f"Coluna: {col}")
    print(df_churn[col].unique())
    print("-" * 30)

Coluna: id_cliente
['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
------------------------------
Coluna: Churn
['nao' 'sim' '']
------------------------------
Coluna: cliente.genero
['feminino' 'masculino']
------------------------------
Coluna: cliente.idoso
[0 1]
------------------------------
Coluna: cliente.parceiro
['sim' 'nao']
------------------------------
Coluna: cliente.dependentes
['sim' 'nao']
------------------------------
Coluna: cliente.tempo_servico
[9.00e+00 4.00e+00 1.30e+01 3.00e+00 7.10e+01 6.30e+01 7.00e+00      nan
 5.40e+01 7.20e+01 5.00e+00 5.60e+01 3.40e+01 1.00e+00 4.50e+01 5.00e+01
 2.30e+01 5.50e+01 2.60e+01 6.90e+01 1.10e+01 3.70e+01 4.90e+01 6.60e+01
 6.70e+01 2.00e+01 4.30e+01 5.90e+01 1.20e+01 2.70e+01 2.00e+00 2.50e+01
 2.90e+01 1.40e+01 3.50e+01 6.40e+01 3.90e+01 4.00e+01 6.00e+00 3.00e+01
 7.00e+01 5.70e+01 5.80e+01 1.60e+01 3.20e+01 3.30e+01 1.00e+01 2.10e+01
 6.10e+01 1.50e+01 4.40e+01 2.20e+01 2.40e+01 1.90e+01 4.70e+01 6.20e+01
 4.60e+01 5.20e+01 8.00e+00 6.00e+01 4.80e+01 2.80e+01 6.50e+01 4.10e+01
 5.30e+01 6.80e+01 5.10e+01 3.10e+01 3.60e+01 1.70e+01 1.80e+01 3.80e+01
 4.20e+01 1.08e+03 1.00e+03 9.50e+02 2.54e+02 3.21e+02 6.50e+02 7.00e+02
 7.21e+02 5.55e+02 4.33e+02 5.12e+02]
------------------------------
Coluna: telefone.servico_telefone
['sim' 'nao']
------------------------------
Coluna: telefone.varias_linhas
['nao' 'sim' 'sem servico de telefone']
------------------------------
Coluna: internet.servico_internet
['DSL' 'fibra otica' 'nao']
------------------------------
Coluna: internet.seguranca_online
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.backup_online
['sim' 'nao' 'sem servico de internet']
------------------------------
Coluna: internet.protecao_dispositivo
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: internet.suporte_tecnico
['sim' 'nao' 'sem servico de internet']
------------------------------
Coluna: internet.tv_streaming
['sim' 'nao' 'sem servico de internet']
------------------------------
Coluna: internet.filmes_streaming
['nao' 'sim' 'sem servico de internet']
------------------------------
Coluna: conta.contrato
[None 'mes a mes' 'dois anos' 'um ano']
------------------------------
Coluna: conta.faturamente_eletronico
[None 'nao' 'sim']
------------------------------
Coluna: conta.metodo_pagamento
[None 'cheque pelo correio' 'cheque eletronico'
 'cartao de credito (automatico)' 'transferencia bancaria (automatica)']
------------------------------
Coluna: conta.cobranca.mensal
[  nan 59.9  73.9  ... 91.75 68.8  67.85]
------------------------------
Coluna: conta.cobranca.Total
[    nan  542.4   280.85 ...  742.9  4627.65 3707.6 ]
------------------------------

In [73]:
df_churn.query("Churn == ''")

,id_cliente,Churn,cliente.genero,cliente.idoso,cliente.parceiro,cliente.dependentes,cliente.tempo_servico,telefone.servico_telefone,telefone.varias_linhas,internet.servico_internet,...,internet.backup_online,internet.protecao_dispositivo,internet.suporte_tecnico,internet.tv_streaming,internet.filmes_streaming,conta.contrato,conta.faturamente_eletronico,conta.metodo_pagamento,conta.cobranca.mensal,conta.cobranca.Total
30,0047-ZHDTW,,feminino,0,nao,nao,11.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,transferencia bancaria (automatica),79.00,929.30
75,0120-YZLQA,,masculino,0,nao,nao,71.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,cartao de credito (automatico),19.90,1355.10
96,0154-QYHJU,,masculino,0,nao,nao,29.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,um ano,sim,cheque eletronico,58.75,1696.20
98,0162-RZGMZ,,feminino,1,nao,nao,5.0,sim,nao,DSL,...,sim,nao,sim,nao,nao,mes a mes,nao,cartao de credito (automatico),59.90,287.85
175,0274-VVQOQ,,masculino,1,sim,nao,65.0,sim,sim,fibra otica,...,sim,sim,nao,sim,sim,um ano,sim,transferencia bancaria (automatica),103.15,6792.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7211,9920-GNDMB,,masculino,0,nao,nao,9.0,sim,sim,fibra otica,...,nao,nao,nao,nao,nao,mes a mes,sim,cheque eletronico,76.25,684.85
7239,9955-RVWSC,,feminino,0,sim,sim,67.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,dois anos,sim,transferencia bancaria (automatica),19.25,1372.90
7247,9966-VYRTZ,,feminino,0,sim,sim,31.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,mes a mes,sim,cheque pelo correio,19.55,658.95
7267,6532-YOHZY,,masculino,0,sim,sim,45.0,sim,sim,fibra otica,...,sim,sim,sim,sim,sim,dois anos,sim,transferencia bancaria (automatica),109.75,4900.65
7342,3601-UTZXO,,masculino,0,sim,sim,41.0,sim,nao,nao,...,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,sem servico de internet,um ano,nao,transferencia bancaria (automatica),19.50,798.20

In [74]:
df_churn_removendo_vazios = df_churn[df_churn['Churn'] !=''].copy()

In [75]:
df_churn_removendo_vazios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7118 entries, 0 to 7343
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id_cliente                     7118 non-null   object
 1   Churn                          7118 non-null   object
 2   cliente.genero                 7118 non-null   object
 3   cliente.idoso                  7118 non-null   int64
 4   cliente.parceiro               7118 non-null   object
 5   cliente.dependentes            7118 non-null   object
 6   cliente.tempo_servico          7110 non-null   float64
 7   telefone.servico_telefone      7118 non-null   object
 8   telefone.varias_linhas         7118 non-null   object
 9   internet.servico_internet      7118 non-null   object
 10  internet.seguranca_online      7118 non-null   object
 11  internet.backup_online         7118 non-null   object
 12  internet.protecao_dispositivo  7118 non-null   object
 13  internet.suporte_tecnico       7118 non-null   object
 14  internet.tv_streaming          7118 non-null   object
 15  internet.filmes_streaming      7118 non-null   object
 16  conta.contrato                 7086 non-null   object
 17  conta.faturamente_eletronico   7100 non-null   object
 18  conta.metodo_pagamento         7091 non-null   object
 19  conta.cobranca.mensal          7100 non-null   float64
 20  conta.cobranca.Total           7102 non-null   float64
dtypes: float64(3), int64(1), object(17)
memory usage: 1.2+ MB

In [76]:
df_churn_removendo_vazios.reset_index(drop=True,inplace=True)